#!/bin/bash

# this script is used to identify the relation among functions 
# before run this script you should execute the calltrace pin-tool
# input the calltrace file (calls.txt) generated by calltrace pin-tool.
# output the calltree (calls.txt.sort-calltrace) and run time calls of 
# the requested function
#

if [ $# -lt 2 ]; then 
	echo "Usage: $0 calltrace-file function "
	exit 1
fi

log_file="$1.sort"


# pin -mt -follow_execv -t $current_dir"/calltrace.so" -- $2
# ./example

sort $1 | uniq > $log_file
./relation $log_file > $log_file"-calltree"
grep $2 $log_file"-calltree" > $1"-"$2"-function-calltree"
exit 0
